# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/cask-fonts"
tap "schniz/tap"

# packages
brew "ack"
brew "bat"
brew "cloc"
brew "diff-so-fancy"
brew "entr"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "gnupg"
brew "grep"
brew "highlight"
brew "htop"
brew "hub"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "markdown"
brew "mas"
brew "neofetch"
brew "nmap"
brew "noti"
brew "python"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "schniz/tap/fnm"
brew "shellcheck"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "vim"
brew "wdiff"
brew "wget"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "nvm"

# Applications
cask "notion"
#cask "rocket"
cask "postman"
cask "insomnia"
cask "visual-studio-code"
cask "docker"
cask "alacritty"
cask "dbeaver-community"
cask "iterm2"
cask "spark"

# Browsers
cask "firefox"
cask "google-chrome"

# Fonts
cask "font-hack-nerd-font"

# macOS App Store
mas "Xcode", id: 497799835